### ISSUE TITLE
get incorrect key when two fields have the same value

### ISSUE THREAD

**Issue by patricksuo** [jamieomatthews/validation#1]
`Validation.getKeyForField` compare `v.Obj` 's filed value to passedField value to figure out the key. If two fields have the same value, it picks the first matched field and may return an incorrect key. 

``` go
package main

import (
        "fmt"

        //"github.com/jamieomatthews/validation"
        "github.com/sillyousu/validation"
)

type User struct {
        Name string `form:"username"`
        NickName string `form:"nickname"`
}

func main() {
        user := &User{Name: "su21", NickName: "su21"}
       //I want to get an empty `validation.Errors{}` 
        errors := validation.NewErrors()
        v := validation.New(errors, user)
        v.Validate(user.NickName).MinLength(5)

        fmt.Println("============")
        for i := 0; i < v.Errors.Len(); i++ {
                err := v.Errors.At(i)
                fmt.Printf("\nerr: %#v\n", err)
        }
}
```

Result

```
TypeObj: *main.User
Field: su21  passedField: su21
Is Equal!!
Got Key?  username
Min Length: ' su21 '
============

err: &validation.error{fields:[]string{"username"}, classification:"", message:"Minimum Length is 5"}
```

I think  `v.Validate("FieldName")` is more reasonable.

**Comment by jamieomatthews** [comment]
Yeah, I was experimenting with this.  I will try to keep experimental things on the development branch from now on.  I'll be doing some work with Matt tonight in integrating this into Martini Bind package as well.  I'll update you on this thread when I have things working again

**Comment by jamieomatthews** [comment]
@sillyousu I have update the code a bit, Matt Holt and I are working out how this will interact with Martini.  For now it seems to be working again, but I added a convenience .Key() method that you can call to set the default key.  Check out the test file.  

I'm being held up a bit by going back and forth with the martini.bind package, because we have to get that right.  After that, this package will come up to working order very quickly.  Thank you for you patents.
